{
 "title": "http_logs dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rows per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "logs",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "  SELECT (intDiv(toUInt32(timestamp), 60) * 60) * 1000 AS t,\r\n         count() AS rows_per_minute\r\n  FROM logs.http_log\r\n  WHERE $timeFilter\r\n  GROUP BY t\r\n  ORDER BY t",
     "rawQuery": "SELECT (intDiv(toUInt32(timestamp), 60) * 60) * 1000 AS t,\r\n         count() AS rows_per_minute\r\n  FROM logs.http_log\r\n  WHERE timestamp >= toDateTime(1755002566) AND timestamp <= toDateTime(1755024166)\r\n  GROUP BY t\r\n  ORDER BY t",
     "round": "0s",
     "table": "http_log"
    }
   ]
  },
  {
   "title": "requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "logs",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "  SELECT (intDiv(toUInt32(timestamp), 60) * 60) * 1000 AS t,\n         count() / 60.0 AS rps\n  FROM logs.http_log\n  WHERE $timeFilter\n  GROUP BY t\n  ORDER BY t",
     "rawQuery": "SELECT (intDiv(toUInt32(timestamp), 60) * 60) * 1000 AS t,\n         count() / 60.0 AS rps\n  FROM logs.http_log\n  WHERE timestamp >= toDateTime(1755002544) AND timestamp <= toDateTime(1755024144)\n  GROUP BY t\n  ORDER BY t",
     "round": "0s",
     "table": "http_log"
    }
   ]
  },
  {
   "title": "bytes per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "database": "logs",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "  SELECT (intDiv(toUInt32(timestamp), 60) * 60) * 1000 AS t,\r\n         sum(bytes_sent) AS bytes_per_minute\r\n  FROM logs.http_log\r\n  WHERE $timeFilter\r\n  GROUP BY t\r\n  ORDER BY t",
     "rawQuery": "SELECT (intDiv(toUInt32(timestamp), 60) * 60) * 1000 AS t,\r\n         sum(bytes_sent) AS bytes_per_minute\r\n  FROM logs.http_log\r\n  WHERE timestamp >= toDateTime(1755002578) AND timestamp <= toDateTime(1755024178)\r\n  GROUP BY t\r\n  ORDER BY t",
     "round": "0s",
     "table": "http_log"
    }
   ]
  },
  {
   "title": "E2E latency (p50/p90/p99) seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "database": "logs",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT (intDiv(toUInt32(ingested_at), 60) * 60) * 1000 AS t, quantileTDigest(0.5)(ingested_at - timestamp) AS p50_s FROM logs.http_log WHERE $timeFilterByColumn(ingested_at) AND (ingested_at - timestamp) BETWEEN 0 AND 7200 GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "http_log"
    },
    {
     "database": "logs",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "query": "SELECT (intDiv(toUInt32(ingested_at), 60) * 60) * 1000 AS t, quantileTDigest(0.9)(ingested_at - timestamp) AS p90_s FROM logs.http_log WHERE $timeFilterByColumn(ingested_at) AND (ingested_at - timestamp) BETWEEN 0 AND 7200 GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "http_log"
    },
    {
     "database": "logs",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "query": "SELECT (intDiv(toUInt32(ingested_at), 60) * 60) * 1000 AS t, quantileTDigest(0.99)(ingested_at - timestamp) AS p99_s FROM logs.http_log WHERE $timeFilterByColumn(ingested_at) AND (ingested_at - timestamp) BETWEEN 0 AND 7200 GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "http_log"
    }
   ]
  }
 ]
}